// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Read Supabase connection details from Vite environment variables.
// Make sure you have VITE_SUPABASE_URL and VITE_SUPABASE_PUBLISHABLE_KEY set in your .env
// Example in .env:
// VITE_SUPABASE_URL="https://your-project.supabase.co"
// VITE_SUPABASE_PUBLISHABLE_KEY="your-public-anon-key"

const SUPABASE_URL = (import.meta.env.VITE_SUPABASE_URL as string) || '';
const SUPABASE_PUBLISHABLE_KEY = (import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY as string) || '';

if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  // Throwing here makes misconfiguration obvious during development.
  // In production, ensure env vars are provided by your deployment platform.
  throw new Error('Missing VITE_SUPABASE_URL or VITE_SUPABASE_PUBLISHABLE_KEY environment variables');
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});